---

- name: add php5 repo for ubuntu
  shell: LC_ALL=C.UTF-8 /usr/bin/add-apt-repository -y {{ item }}
  with_items:
    - 'ppa:ondrej/php5' 
    - 'ppa:ondrej/systemd'
  when: ansible_distribution == 'Ubuntu'

- name: add php5.5 key from dotdeb for debian
  shell: curl -O http://www.dotdeb.org/dotdeb.gpg && apt-key add dotdeb.gpg
  when: ansible_distribution == 'Debian'

- name: add php5.5 source from dotdeb for debian
  shell: echo 'deb http://packages.dotdeb.org wheezy-php55 all' > /etc/apt/sources.list.d/php55.list && chmod 0644 /etc/apt/sources.list.d/php55.list
  when: ansible_distribution == 'Debian'

- name: apt-get update
  command: apt-get update

- name: install php5 related packages
  apt: pkg={{ item }} state=latest
  with_items:
    - php5
    - php5-mcrypt
    - php-xml-parser
    - php5-xdebug
    - php5-mysql
    - php5-cli
    - php5-curl
    - php5-fpm
    - libssh2-1-dev
    - php5-apcu
    - php-pear
    - php5-gd
    - php5-imagick

- include: pear.yml

