---

- name: add php5 repo
  shell: /usr/bin/add-apt-repository ppa:ondrej/php5 && /usr/bin/add-apt-repository ppa:ondrej/systemd

- name: apt-get update
  command: apt-get update

- name: install php5 related packages
  apt: pkg={{ item }} state=latest
  with_items:
    - php5
    - php5-mcrypt
    - php-xml-parser
    - php5-xdebug
    - php5-mysql
    - php5-cli
    - php5-curl
    - php5-fpm
    - libssh2-1-dev
    - php-apc
    - php-pear
    - php5-gd
    - php5-imagick

- include: pear.yml

