---

- name: deploy everything to vm
  hosts: laravel 

  roles:
    #- common
    #- avahi#-daemon
    #- MySQL
    #- php
    - nginx
    #- supervisor
    #- sphinx
    #- redis
    #- nodejs
    #- composer
    #- beanstalkd

